### ISSUE TITLE
uninitialized constant OdpsDatahub::CrcCalculator::Error

### ISSUE THREAD

**Issue by menghuanwd** [aliyun/aliyun-odps-fluentd-plugin#5]
2016-06-17 13:28:23 +0800 [error]: unexpected error error_class=RuntimeError error="uninitialized constant OdpsDatahub::CrcCalculator::Error\nDid you mean?  KeyError\n               IOError\n               Errno"
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-aliyun-odps-0.1.6/lib/fluent/plugin/out_aliyun_odps.rb:328:in `rescue in start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluent-plugin-aliyun-odps-0.1.6/lib/fluent/plugin/out_aliyun_odps.rb:325:in`start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:138:in`block in start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:127:in `block (2 levels) in lifecycle'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:126:in`each'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:126:in `block in lifecycle'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:113:in`each'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:113:in `lifecycle'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/root_agent.rb:137:in`start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/engine.rb:211:in `start'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/engine.rb:175:in`run'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:580:in `run_engine'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:382:in`block in run_worker'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:509:in `main_process'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/supervisor.rb:378:in`run_worker'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/lib/fluent/command/fluentd.rb:266:in `<top (required)>'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fluentd-0.14.0/bin/fluentd:5:in`<top (required)>'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/bin/fluentd:22:in `load'
  2016-06-17 13:28:23 +0800 [error]: /Users/guyifeng/.rbenv/versions/2.3.0/bin/fluentd:22:in`<main>'

fluentd.conf:

<source>
   @type tail
   path /Users/guyifeng/workspace/HugoCount/docs/user_visits.csv
   pos_file /Users/guyifeng/workspace/HugoCount/docs/user_visits.csv.pos
   refresh_interval 5s
   tag user_visits.csv
   format csv
</source>
<match user_visits.**>
  @type aliyun_odps
  aliyun_access_id ******
  aliyun_access_key *******
  aliyun_odps_endpoint http://service.odps.aliyun.com/api
  aliyun_odps_hub_endpoint http://dh.odps.aliyun.com
  buffer_chunk_limit 2m
  buffer_queue_limit 128
  flush_interval 5s
  project devel_statistics
  enable_fast_crc true
  <table user_visits.csv>
    table user_visits
    fields created_at,title,url,ip,request_uri,origin,referer,user_agent
    shard_number 1
    retry_time 3
    retry_interval 1
    abandon_mode true
  </table>
</match>

这个我该怎么处理呢？

**Comment by dongxiao1198** [comment]
这个应该是在获取系统类型的时候抛错了，你是什么系统

**Comment by dongxiao1198** [comment]
可以先把enable_fast_crc false关掉
